import type { Course } from "@/types/courses";

export const MOCK_COURSES: Course[] = [
  {
    id: 1,
    title: "The Complete React Developer Bootcamp",
    description:
      "Master React from scratch. Build real-world projects with hooks, context, Redux, and more. Go from zero to job-ready.",
    category: "Web Development",
    tag: "React",
    imgUrl: "https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=800&auto=format&fit=crop",
    level: "Beginner",
    duration: 1440,
    modules: [
      "Getting Started with React",
      "JSX & Components",
      "State & Props",
      "Hooks Deep Dive",
      "React Router",
      "Context API",
      "Redux Toolkit",
      "Final Project",
    ],
    rating: 4.8,
    reviews: 3241,
    enrolled: 18920,
    price: 0,
    isFree: true,
    isFeatured: true,
    language: "English",
    instructor: {
      name: "Sarah Johnson",
      avatar: "https://i.pravatar.cc/150?img=47",
      bio: "Senior Frontend Engineer with 10+ years of experience. Passionate about teaching modern web technologies.",
    },
    createdAt: "2024-01-15T08:00:00Z",
  },
  {
    id: 2,
    title: "Python for Data Science & Machine Learning",
    description:
      "Learn Python, Pandas, NumPy, Matplotlib, and Scikit-learn to analyze data and build ML models from the ground up.",
    category: "Data Science",
    tag: "Python",
    imgUrl: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&auto=format&fit=crop",
    level: "Intermediate",
    duration: 2160,
    modules: [
      "Python Refresher",
      "NumPy & Pandas",
      "Data Visualization",
      "Statistics for ML",
      "Supervised Learning",
      "Unsupervised Learning",
      "Model Evaluation",
      "Capstone Project",
    ],
    rating: 4.9,
    reviews: 5810,
    enrolled: 34500,
    price: 49.99,
    isFree: false,
    isFeatured: true,
    language: "English",
    instructor: {
      name: "Dr. Alan Park",
      avatar: "https://i.pravatar.cc/150?img=12",
      bio: "PhD in Computer Science. Former ML engineer at Google. Loves making complex topics simple.",
    },
    createdAt: "2024-02-20T10:00:00Z",
  },
  {
    id: 3,
    title: "UI/UX Design Fundamentals with Figma",
    description:
      "Learn the principles of great design and how to use Figma to create stunning prototypes and design systems.",
    category: "UI/UX",
    tag: "Figma",
    imgUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&auto=format&fit=crop",
    level: "Beginner",
    duration: 900,
    modules: [
      "Design Thinking",
      "Typography & Color",
      "Layout & Grids",
      "Figma Basics",
      "Component Libraries",
      "Prototyping",
      "User Testing",
    ],
    rating: 4.7,
    reviews: 2108,
    enrolled: 12400,
    price: 29.99,
    isFree: false,
    isFeatured: false,
    language: "English",
    instructor: {
      name: "Mia Chen",
      avatar: "https://i.pravatar.cc/150?img=33",
      bio: "Product designer at Airbnb. Loves crafting intuitive, beautiful digital experiences.",
    },
    createdAt: "2024-03-05T09:00:00Z",
  },
  {
    id: 4,
    title: "iOS App Development with Swift & SwiftUI",
    description:
      "Build fully functional iOS apps using Swift and SwiftUI. Publish your first app to the App Store by the end of this course.",
    category: "Mobile Development",
    tag: "Swift",
    imgUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&auto=format&fit=crop",
    level: "Intermediate",
    duration: 1800,
    modules: [
      "Swift Basics",
      "SwiftUI Views",
      "Navigation & State",
      "Networking",
      "Core Data",
      "Animations",
      "App Store Submission",
    ],
    rating: 4.6,
    reviews: 1432,
    enrolled: 8750,
    price: 39.99,
    isFree: false,
    isFeatured: false,
    language: "English",
    instructor: {
      name: "Jake Thompson",
      avatar: "https://i.pravatar.cc/150?img=7",
      bio: "iOS developer with 8 years of experience. Has shipped 20+ apps on the App Store.",
    },
    createdAt: "2024-04-10T11:00:00Z",
  },
  {
    id: 5,
    title: "Digital Marketing Masterclass",
    description:
      "From SEO and social media to email campaigns and paid ads — learn every channel to grow any business online.",
    category: "Digital Marketing",
    tag: "Marketing",
    imgUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop",
    level: "Beginner",
    duration: 720,
    modules: [
      "Marketing Fundamentals",
      "SEO & Content",
      "Social Media Strategy",
      "Email Marketing",
      "Google Ads",
      "Analytics & Reporting",
    ],
    rating: 4.5,
    reviews: 3910,
    enrolled: 22100,
    price: 0,
    isFree: true,
    isFeatured: true,
    language: "English",
    instructor: {
      name: "Rachel Green",
      avatar: "https://i.pravatar.cc/150?img=56",
      bio: "CMO turned educator. Helped 50+ startups scale their online presence.",
    },
    createdAt: "2024-05-01T08:30:00Z",
  },
  {
    id: 6,
    title: "Introduction to Artificial Intelligence",
    description:
      "Understand the core concepts of AI — from neural networks and NLP to ethics and the future of intelligent systems.",
    category: "AI",
    tag: "AI",
    imgUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&auto=format&fit=crop",
    level: "Beginner",
    duration: 600,
    modules: [
      "What is AI?",
      "Search Algorithms",
      "Machine Learning Overview",
      "Neural Networks",
      "NLP Basics",
      "Computer Vision",
      "AI Ethics",
    ],
    rating: 4.8,
    reviews: 4502,
    enrolled: 28300,
    price: 19.99,
    isFree: false,
    isFeatured: true,
    language: "English",
    instructor: {
      name: "Prof. Lisa Wang",
      avatar: "https://i.pravatar.cc/150?img=44",
      bio: "AI researcher and professor at MIT. Passionate about democratising AI education.",
    },
    createdAt: "2024-06-12T07:00:00Z",
  },
  {
    id: 7,
    title: "Photography for Beginners: From Auto to Manual",
    description:
      "Take stunning photos with any camera. Learn composition, lighting, exposure, and post-processing in Lightroom.",
    category: "Photography",
    tag: "Photography",
    imgUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop",
    level: "Beginner",
    duration: 480,
    modules: [
      "Understanding Your Camera",
      "Exposure Triangle",
      "Composition Rules",
      "Lighting Techniques",
      "Portrait Photography",
      "Landscape Photography",
      "Editing in Lightroom",
    ],
    rating: 4.7,
    reviews: 1870,
    enrolled: 10500,
    price: 0,
    isFree: true,
    isFeatured: false,
    language: "English",
    instructor: {
      name: "Marco Rossi",
      avatar: "https://i.pravatar.cc/150?img=68",
      bio: "Award-winning travel photographer. Shot for National Geographic and Vogue.",
    },
    createdAt: "2024-07-08T14:00:00Z",
  },
  {
    id: 8,
    title: "Full-Stack Web Development with Node.js",
    description:
      "Build scalable full-stack apps with Node.js, Express, MongoDB, and React. Deploy to the cloud with confidence.",
    category: "Web Development",
    tag: "Node.js",
    imgUrl: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&auto=format&fit=crop",
    level: "Advanced",
    duration: 2400,
    modules: [
      "Node.js Core",
      "Express & REST APIs",
      "MongoDB & Mongoose",
      "Authentication & JWT",
      "React Frontend",
      "File Uploads & Storage",
      "Deployment & DevOps",
    ],
    rating: 4.9,
    reviews: 6120,
    enrolled: 41000,
    price: 59.99,
    isFree: false,
    isFeatured: true,
    language: "English",
    instructor: {
      name: "David Kim",
      avatar: "https://i.pravatar.cc/150?img=15",
      bio: "Full-stack architect with 12 years of experience. Loves building and teaching scalable systems.",
    },
    createdAt: "2024-08-20T10:00:00Z",
  },
  {
    id: 9,
    title: "Personal Finance & Investing 101",
    description:
      "Learn to budget, save, invest, and grow your wealth. From stocks and ETFs to crypto and retirement planning.",
    category: "Finance",
    tag: "Finance",
    imgUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop",
    level: "Beginner",
    duration: 540,
    modules: [
      "Budgeting Basics",
      "Emergency Funds",
      "Stock Market 101",
      "ETFs & Index Funds",
      "Crypto Fundamentals",
      "Retirement Planning",
    ],
    rating: 4.6,
    reviews: 2340,
    enrolled: 15800,
    price: 24.99,
    isFree: false,
    isFeatured: false,
    language: "English",
    instructor: {
      name: "Nina Patel",
      avatar: "https://i.pravatar.cc/150?img=39",
      bio: "Certified Financial Planner with 15 years of experience helping individuals build wealth.",
    },
    createdAt: "2024-09-01T09:00:00Z",
  },
  {
    id: 10,
    title: "Graphic Design with Adobe Illustrator",
    description:
      "Master vector graphics, logo design, branding, and illustration from scratch using Adobe Illustrator.",
    category: "Graphic Design",
    tag: "Illustrator",
    imgUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop",
    level: "Intermediate",
    duration: 1080,
    modules: [
      "Illustrator Interface",
      "Shapes & Paths",
      "Typography Design",
      "Logo Design",
      "Color Theory",
      "Brand Identity",
      "Portfolio Project",
    ],
    rating: 4.5,
    reviews: 1590,
    enrolled: 9200,
    price: 34.99,
    isFree: false,
    isFeatured: false,
    language: "English",
    instructor: {
      name: "Aisha Diallo",
      avatar: "https://i.pravatar.cc/150?img=25",
      bio: "Creative director and brand designer with clients across 30+ countries.",
    },
    createdAt: "2024-09-15T13:00:00Z",
  },
];